# Generated by Django 3.1.2 on 2020-10-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201017_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=1000)),
                ('video_url', models.CharField(max_length=1000)),
                ('typecourse', models.CharField(choices=[('free', 'free'), ('paid', 'paid')], default='free', max_length=20)),
                ('course_length', models.CharField(max_length=500)),
            ],
        ),
    ]
