# Generated by Django 3.1.2 on 2020-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='your text here ...', max_length=2000),
        ),
    ]
